"""
Django settings for DjangoUserService project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import re
from pathlib import Path

import pymysql
from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values, find_dotenv, load_dotenv

pymysql.install_as_MySQLdb()

load_dotenv_enabled = os.getenv('DJANGO_LOAD_DOTENV', 'true').lower() == 'true'
dotenv_path = find_dotenv() if load_dotenv_enabled else ''
dotenv_environment = dotenv_values(dotenv_path) if dotenv_path else {}

ENVIRONMENT = os.getenv(
    'DJANGO_ENV', dotenv_environment.get('DJANGO_ENV', 'production')
).strip().lower()
if ENVIRONMENT not in {'development', 'production'}:
    raise ImproperlyConfigured('DJANGO_ENV 必须是 development 或 production')
if ENVIRONMENT == 'development' and dotenv_path:
    load_dotenv(dotenv_path)

IS_PRODUCTION = ENVIRONMENT == 'production'


def required_env(name):
    value = os.getenv(name, '').strip()
    if not value:
        raise ImproperlyConfigured(f'生产环境缺少必需配置: {name}')
    return value


def split_env(name, *, required=False, default=''):
    raw_value = required_env(name) if required else os.getenv(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]


def validate_rate(name, value):
    if not re.fullmatch(r'[1-9]\d*/(second|minute|hour|day)', value):
        raise ImproperlyConfigured(f'{name} 必须使用正整数/时间单位格式')
    return value


def validate_secret(name, value):
    if (
        len(value) < 50
        or len(set(value)) < 5
        or value.startswith('django-insecure-')
        or 'YOUR_' in value.upper()
    ):
        raise ImproperlyConfigured(f'{name} 不满足生产强度要求')
    return value


def positive_int(name, default):
    try:
        value = int(os.getenv(name, default))
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} 必须是正整数') from exc
    if value <= 0:
        raise ImproperlyConfigured(f'{name} 必须大于 0')
    return value


def shared_cache_key(key, key_prefix, version):
    if key.startswith('jwt:revoked:'):
        return key
    return f'{key_prefix}:{version}:{key}'


if IS_PRODUCTION:
    django_secret_key = validate_secret(
        'DJANGO_SECRET_KEY', required_env('DJANGO_SECRET_KEY')
    )
    jwt_secret_key = validate_secret(
        'JWT_SECRET_KEY', required_env('JWT_SECRET_KEY')
    )
    if django_secret_key == jwt_secret_key:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY 与 JWT_SECRET_KEY 必须不同')

    allowed_hosts = split_env('DJANGO_ALLOWED_HOSTS', required=True)
    if '*' in allowed_hosts:
        raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS 禁止使用通配符')

    cors_allowed_origins = split_env(
        'DJANGO_CORS_ALLOWED_ORIGINS', required=True
    )
    if any(not origin.startswith('https://') for origin in cors_allowed_origins):
        raise ImproperlyConfigured('生产 CORS 来源必须使用 HTTPS')

    anonymous_rate = validate_rate(
        'DJANGO_ANON_RATE', required_env('DJANGO_ANON_RATE')
    )
    user_rate = validate_rate(
        'DJANGO_USER_RATE', required_env('DJANGO_USER_RATE')
    )
    redis_cache_url = required_env('REDIS_CACHE_URL')
else:
    django_secret_key = os.getenv(
        'DJANGO_SECRET_KEY', 'development-only-django-secret-key'
    )
    jwt_secret_key = os.getenv(
        'JWT_SECRET_KEY', 'development-only-jwt-secret-key'
    )
    allowed_hosts = split_env(
        'DJANGO_ALLOWED_HOSTS', default='127.0.0.1,localhost,testserver'
    )
    cors_allowed_origins = split_env(
        'DJANGO_CORS_ALLOWED_ORIGINS',
        default='http://127.0.0.1:5173,http://localhost:5173',
    )
    anonymous_rate = validate_rate(
        'DJANGO_ANON_RATE', os.getenv('DJANGO_ANON_RATE', '1000/minute')
    )
    user_rate = validate_rate(
        'DJANGO_USER_RATE', os.getenv('DJANGO_USER_RATE', '3000/minute')
    )
    redis_cache_url = os.getenv('REDIS_CACHE_URL', '').strip()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django_secret_key
JWT_SECRET_KEY = jwt_secret_key
JWT_ALGORITHM = 'HS256'
JWT_TOKEN_TTL_SECONDS = positive_int('JWT_TOKEN_TTL_SECONDS', '86400')

# SECURITY WARNING: don't run with debug turned on in production!
if IS_PRODUCTION:
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = allowed_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'apps.user',
    'apps.file',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoUserService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoUserService.wsgi.application'

# settings.py
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci',
        },
    }
}

# Celery 配置
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
# 统一时区设置
CELERY_TIMEZONE = 'Asia/Shanghai'
# 启用UTC
CELERY_ENABLE_UTC = False
# 设置任务队列
CELERY_TASK_QUEUES = {
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
    'email': {
        'exchange': 'email',
        'routing_key': 'email.tasks',
    }
}
# 设置任务路由
CELERY_TASK_ROUTES = {
}
# 任务执行超时时间（秒）
CELERY_TASK_TIME_LIMIT = 10
# 任务软超时时间（秒）
CELERY_TASK_SOFT_TIME_LIMIT = 8
# 任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600

# redis缓存设置
if redis_cache_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': redis_cache_url,
            'KEY_FUNCTION': 'DjangoUserService.settings.shared_cache_key',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'rag-note-development',
            'KEY_FUNCTION': 'DjangoUserService.settings.shared_cache_key',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# 语言编码
LANGUAGE_CODE = 'zh-hans'

# 统一使用上海时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
# 禁用时区支持，与Celery配置保持一致
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = cors_allowed_origins
CORS_ALLOW_CREDENTIALS = False
CSRF_TRUSTED_ORIGINS = split_env(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default=','.join(cors_allowed_origins),
)

# 覆盖默认的用户模型
AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.user.authentications.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': anonymous_rate,
        'user': user_rate,
    },
    # 3. 全局分页
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 每页默认显示数量
    'PAGE_SIZE': 10
}

APPEND_SLASH = True

if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = positive_int('DJANGO_HSTS_SECONDS', '3600')
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

if os.getenv('DJANGO_TRUST_PROXY_HEADERS', '').lower() == 'true':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
